Spring MVC Controller Advice: Use a ControllerExceptionHandler class annotated with @ControllerAdvice to avoid duplicating code across Controller classes ----------------------------
	Setup a 'GLOBAL' type ExceptionHandler, because otherwise if your application grows, you will end up duplicating this code in all Controllers where a id of type Long is used!
	So we will move the previous NumberFormatException ExceptionHandler to its own class which will be used by all Controllers in the 'controller' package.

	To make sure that it is triggered for all Controllers you add the annotation @ControllerAdvice on class level.

	@Slf4j
	@ControllerAdvice
	public class ControllerExceptionHandler {

		@ExceptionHandler(NumberFormatException.class)
		@ResponseStatus(HttpStatus.BAD_REQUEST)
		public ModelAndView handleNumberFormatException(Exception exception) {
			log.warn("Handling NumberFormatException");
			log.warn(exception.getMessage());
			ModelAndView mav = new ModelAndView("400");
			mav.addObject("exception", exception);

			return mav;
		}
	}

	But now all tests on the 400 page will fail with this error:

		java.lang.AssertionError: No ModelAndView found

		at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:37)
		at org.springframework.test.web.servlet.result.ViewResultMatchers.lambda$name$1(ViewResultMatchers.java:67)
		at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:196)
		at guru.springframework.spring5recipeapp.controller.RecipeControllerTest.showRecipeDetail_Should_Return_A_400_For_String_Id(RecipeControllerTest.java:101)
		...

	The reason for this is that we didn't wire in the Controller Advice in our MockMvc setup.

		mockMvc = MockMvcBuilders.standaloneSetup(recipeController).build();

	When we wire it in, this becomes:

		mockMvc = MockMvcBuilders.standaloneSetup(recipeController)
								.setControllerAdvice(new ControllerExceptionHandler())
								.build();

	PLEASE NOTE: You need to do this wiring in in the MockMvc setup of ALL CONTROLLER TESTS FOR CONTROLLERS which use Long id values in @PathVariable