Pro Tips - Using Settters for JPA Bidirectional Relationships -------------------------------------------------------------
	* Create convenience methods in a centralized location to make sure the bi-directional setters are triggered! Don't rely on people to remember to do it.

		Use convenience methods with the 'add' prefix to indicate that there are side effects going on instead of pure setters.
		It may also be a good idea to return your entity object. This not only makes it more clear that this isn't a standard setter methods, but will allow you to chain method calls.

		Example:

			@Entity
			public class Recipe {

				...
			    public Recipe addNotes(Notes notes) {
					this.setNotes(notes);
					notes.setRecipe(this);				// Automatically take care of the reverse relationship

					return Recipe;
				}
				...
				public Recipe addIngredient (Ingredient ingredient) {
					this.ingredients.add(ingredient);
					ingredient.setRecipe(this);

					return this;
				}
				...
			}

		NOTE: This even allows you to provide a similar convenience method on the other end of the relationship, by re-using the first convenience method!
			Imagine this:
				Recipe {
					public Recipe addCategory(Category cat) {
						this.getCategories.add(cat);
						cat.getRecipes().add(this);

						return this;
					}
				}

				Category {
					public Category addRecipe(Recipe rec) {
						rec.addCategory(this);

						return this;
					}

				}

	BUT BE VERY WARY OF THE HIBERNATE SESSION DEMON WHEN LAZY LOADING ENTITIES!!!

	ERROR:

		2020-09-07 09:48:45.624  WARN 29568 --- [  restartedMain] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [HikariPool-1 housekeeper] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
		...
		2020-09-07 09:48:45.624  WARN 29568 --- [  restartedMain] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [HikariPool-1 connection adder] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
		...
		2020-09-07 09:48:45.628  INFO 29568 --- [  restartedMain] ConditionEvaluationReportLoggingListener :

		Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
		2020-09-07 09:48:45.637 ERROR 29568 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

		org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: guru.springframework.spring5recipeapp.domain.Category.recipes, could not initialize proxy - no Session
			at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:606) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
			at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:218) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
			at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:585) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
			at org.hibernate.collection.internal.PersistentSet.add(PersistentSet.java:210) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
			at guru.springframework.spring5recipeapp.domain.Category.addRecipe(Category.java:46) ~[classes/:na]
			at guru.springframework.spring5recipeapp.bootstrap.DataInitializer.getRecipes(DataInitializer.java:68) ~[classes/:na]
			at guru.springframework.spring5recipeapp.bootstrap.DataInitializer.onApplicationEvent(DataInitializer.java:49) ~[classes/:na]
		...

		SOLUTION:
		=========

			1. Start logging the DB queries to get an idea on which query we may need to interven

				# Log Hibernate queries / SQL statements
				logging.level.org.hibernate.SQL=DEBUG

				# Also log prepared statement parameters
				logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

				# Pretty print SQL
				spring.jpa.properties.hibernate.format_sql=true

			2.

				2020-09-07 11:01:02.659 DEBUG 27364 --- [  restartedMain] org.hibernate.SQL                        :
					select
						category0_.id as id1_0_,
						category0_.name as name2_0_
					from
						category category0_
					where
						category0_.name=?
				2020-09-07 11:01:02.659 TRACE 27364 --- [  restartedMain] o.h.type.descriptor.sql.BasicBinder      : binding parameter [1] as [VARCHAR] - [Mexican]

			3. Try to fix the issue by using an entity graph to force hibernate to load the associated recipes when loading a category from the DB.
				In essence you force eager loading for the related property mentioned in the entity graph

				A. Define a named entity graph on the target entity

					@Entity
					@NamedEntityGraph(name = "Category.recipes",
							attributeNodes = @NamedAttributeNode("recipes")
					)
					public class Category {}

				B. Tell Hibernate to use this entity graph when fetching the data from the database

					public interface CategoryRepository extends CrudRepository<Category, Long> {

						@EntityGraph(value = "Category.recipes")
						Optional<Category> findByName(String name);

					}

					So when we use custom method findByName(String name) from the CategoryRepository, Hibernate will also fetch the associated recipe objects!

					You can see this in the now changed database query which mentions all recipe fields now as well

						2020-09-07 10:58:16.221 DEBUG 9856 --- [  restartedMain] org.hibernate.SQL                        :
							select
								category0_.id as id1_0_0_,
								recipe2_.id as id1_3_1_,
								category0_.name as name2_0_0_,
								recipe2_.cook_instructions as cook_ins2_3_1_,
								recipe2_.cook_time_mins as cook_tim3_3_1_,
								recipe2_.description as descript4_3_1_,
								recipe2_.difficulty as difficul5_3_1_,
								recipe2_.image as image6_3_1_,
								recipe2_.name as name7_3_1_,
								recipe2_.notes_id as notes_i12_3_1_,
								recipe2_.prep_time_mins as prep_tim8_3_1_,
								recipe2_.source as source9_3_1_,
								recipe2_.url as url10_3_1_,
								recipe2_.yield as yield11_3_1_,
								recipes1_.category_id as category2_4_0__,
								recipes1_.recipe_id as recipe_i1_4_0__
							from
								category category0_
							left outer join
								recipe_category recipes1_
									on category0_.id=recipes1_.category_id
							left outer join
								recipe recipe2_
									on recipes1_.recipe_id=recipe2_.id
							where
								category0_.name=?
						2020-09-07 10:58:16.222 TRACE 3964 --- [  restartedMain] o.h.type.descriptor.sql.BasicBinder      : binding parameter [1] as [VARCHAR] - [Mexican]