Using Spring MVC Annotation @ResponseStatus -------------------------------------------
	* Add @ResponseStatus NOT_FOUND to custom runtime exception ObjectNotFoundException

		@ResponseStatus(HttpStatus.NOT_FOUND)
		public class ObjectNotFoundException extends RuntimeException {
			public ObjectNotFoundException(String message) {
				super(message);
			}

			public ObjectNotFoundException(String message, Throwable cause) {
				super(message, cause);
			}
		}

		This will set the HTTP response status to 404 in case the Controller encounters this exception.

	* Add Service test for ObjectNotFoundException

		@ExtendWith(MockitoExtension.class)
		class RecipeRepositoryServiceImplTest {

		    @Test
			void findById_Should_Throw_ObjectNotFoundException_For_Unknown_Id() {
				// given
				when(mockRecipeRepository.findById(anyLong())).thenReturn(java.util.Optional.empty());

				// when
				ObjectNotFoundException e = assertThrows(ObjectNotFoundException.class, () -> recipeRepositoryService.findById(ID));

				// then
				assertEquals("No Recipe found for id '" + ID + "'", e.getMessage());
			}
		}

	* Add Controller test for the response status

		@Test
		void showRecipeDetail_Should_Return_A_404_For_Unknown_Id() throws Exception {
			// given
			when(mockRecipeService.findById(anyLong())).thenThrow(ObjectNotFoundException.class);

			// when
			mockMvc.perform(get("/recipes/" + ID))
					.andExpect(status().isNotFound());
		}

	In the application in the browser you will go from this Internal Server Error:

		There was an unexpected error (type=Internal Server Error, status=500).
		No Recipe found for id '666'
		guru.springframework.spring5recipeapp.exception.ObjectNotFoundException: No Recipe found for id '666'
			at guru.springframework.spring5recipeapp.service.RecipeRepositoryServiceImpl.lambda$findById$1(RecipeRepositoryServiceImpl.java:40)

	to this 404 Not Found:
		There was an unexpected error (type=Not Found, status=404).
		No Recipe found for id '666'
		guru.springframework.spring5recipeapp.exception.ObjectNotFoundException: No Recipe found for id '666'
			at guru.springframework.spring5recipeapp.service.RecipeRepositoryServiceImpl.lambda$findById$1(RecipeRepositoryServiceImpl.java:40)