Spring MVC Exception Handler: Show a custom nice 404 page in the browser ----------------------------
	Use @ExceptionHandler Controller method to show a custom nice 404 page.

	* In RecipeController add a method annotated with @ExceptionHandler which returns a dedicated view template '404.html'.

		@ExceptionHandler(ObjectNotFoundException.class)
		public ModelAndView handleObjectNotFound() {
			log.info("Handling not found exception");
			ModelAndView mav = new ModelAndView("404");

			return mav;
		}

	* /src/main/resources/templates/404.html

		<!DOCTYPE html>
		<html lang="en" xmlns:th="http://www.thymeleaf.org">
		<head>
			<meta charset="UTF-8"/>
			<title>404 Not Found Error</title>

			<!-- Add Bootstrap CSS -->
			<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
				  integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
				  crossorigin="anonymous"
				  th:href="@{/webjars/bootstrap/4.5.2/css/bootstrap.min.css}"><!--/* Instruct Thymeleaf to replace this href CDN value with the local webjars reference */-->
			<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
					integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
					crossorigin="anonymous"
					th:src="@{/webjars/jquery/3.5.1/jquery.slim.min.js}"></script><!--/* Instruct Thymeleaf to replace this src CDN value with the local webjars reference */-->
			<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
					integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
					crossorigin="anonymous"></script>
			<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
					integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
					crossorigin="anonymous"
					th:src="@{/webjars/bootstrap/4.5.2/js/bootstrap.min.js}"></script><!--/* Instruct Thymeleaf to replace this src CDN value with the local webjars reference */-->
		</head>
		<body>
			<div class="container-fluid">
				<div class="row">
					<div class="col-lg-10 offset-md-1">
						<h1>404 Not Found</h1>
					</div>
				</div>
			</div>
		</body>
		</html>

	* Extend the previous test, so it also checks if this 404 view is returned

		@Test
		void showRecipeDetail_Should_Return_A_404_For_Unknown_Id() throws Exception {
			// given
			when(mockRecipeService.findById(anyLong())).thenThrow(ObjectNotFoundException.class);

			// when
			mockMvc.perform(get("/recipes/" + ID))
					.andExpect(status().isNotFound())
					.andExpect(view().name("404"));
		}

		TEST RESULT:

			java.lang.AssertionError: Status expected:<404> but was:<200>
			Expected :404
			Actual   :200
			<Click to see difference>

				at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:59)
				at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:122)
				at org.springframework.test.web.servlet.result.StatusResultMatchers.lambda$matcher$9(StatusResultMatchers.java:627)
				at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:196)
				at guru.springframework.spring5recipeapp.controller.RecipeControllerTest.showRecipeDetail_Should_Return_A_404_For_Unknown_Id(RecipeControllerTest.java:92)
				...

		PLEASE NOTE: The @ExceptionHandler has a higher precedence/prio than the @ResponseStatus annotation!!!
		So in the controller you basically have a method which returns a valid view so there is nothing wrong anymore.
		To get the correct 404 response status back, you need to also add that @ResponseStatus(HttpStatus.NOT_FOUND) to this controller method which handles the NotFoundException.

		In RecipeController

			@ExceptionHandler(ObjectNotFoundException.class)
			@ResponseStatus(HttpStatus.NOT_FOUND)
			public ModelAndView handleObjectNotFound() {
				log.info("Handling not found exception");
				ModelAndView mav = new ModelAndView("404");

				return mav;
			}