Pro Tips - Using Settters for JPA Bidirectional Relationships ------------------------------------------------------------- The course instructor solution to this issue
	BUT BE VERY WARY OF THE HIBERNATE SESSION DEMON WHEN LAZY LOADING ENTITIES!!!

ERROR:

		2020-09-07 09:48:45.624  WARN 29568 --- [  restartedMain] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [HikariPool-1 housekeeper] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
		...
		2020-09-07 09:48:45.624  WARN 29568 --- [  restartedMain] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [HikariPool-1 connection adder] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
		...
		2020-09-07 09:48:45.628  INFO 29568 --- [  restartedMain] ConditionEvaluationReportLoggingListener :

		Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
		2020-09-07 09:48:45.637 ERROR 29568 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

		org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: guru.springframework.spring5recipeapp.domain.Category.recipes, could not initialize proxy - no Session
			at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:606) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
			at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:218) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
			at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:585) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
			at org.hibernate.collection.internal.PersistentSet.add(PersistentSet.java:210) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
			at guru.springframework.spring5recipeapp.domain.Category.addRecipe(Category.java:46) ~[classes/:na]
			at guru.springframework.spring5recipeapp.bootstrap.DataInitializer.getRecipes(DataInitializer.java:68) ~[classes/:na]
			at guru.springframework.spring5recipeapp.bootstrap.DataInitializer.onApplicationEvent(DataInitializer.java:49) ~[classes/:na]
		...

		SOLUTION:
		=========

		Course:
			In the getRecipes() method of the DataInitializer, we are performing a calls to recipeRepository.saveAll() method to persist all data at once. Every time we call a repository method we start and end a hibernate transaction.
			At some point in the data initialization we seem to be loading a category which triggers the lazy loading of the associated recipes outside of that Hibernate transaction somewhere.
				public Category addRecipe(Recipe recipe) {
					recipe.addCategory(this);

					return this;
				}

				=>     public Recipe addCategory(Category category) {
							this.categories.add(category);
							category.getRecipes().add(this);				// Here is where we fetch the recipes, which triggers the lazy load.

							return this;
						}

			So, the quickfix is to wrap the onApplicationEvent method in a transaction by manually adding the @Transactional annotation to instruct Spring framework to create a single transaction around that entire method.
			So it will also include wrap the call to getRecipes() and now everything will happen in the same transactional context.

			// Use this for adding example data to a test database
			@Component
			@Slf4j
			public class DataInitializer implements ApplicationListener<ContextRefreshedEvent> {

				...

				@Override
				@Transactional	// org.springframework.transaction.annotation.Transactional;
				public void onApplicationEvent(ContextRefreshedEvent contextRefreshedEvent) {
					log.info("Loading Bootstrap Data...");
					recipeRepository.saveAll(getRecipes());
				}

				private List<Recipe> getRecipes() {
					...
				}
			}

			Personal view: I think this is a hacky quickfix which works, but likely the same problem will bite us in the ass somewhere in the future. :-)